// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(SistemaRhContext))]
    [Migration("20260312164612_AgregarCampoAnioAguinaldos")]
    partial class AgregarCampoAnioAguinaldos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.Aguinaldos", b =>
                {
                    b.Property<int>("IdAguinaldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aguinaldo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAguinaldo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("DiasTrabajados")
                        .HasColumnType("int")
                        .HasColumnName("dias_trabajados");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','CALCULADO','PAGADO')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'CALCULADO'");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_calculo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("MontoAguinaldo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_aguinaldo");

                    b.Property<decimal>("SalarioPromedio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario_promedio");

                    b.HasKey("IdAguinaldo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "Estado" }, "idx_empleado_estado");

                    b.HasIndex(new[] { "FechaPago" }, "idx_fecha_pago");

                    b.ToTable("aguinaldos", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Asistencias", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asistencia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PRESENTE','AUSENTE','TARDANZA','PERMISO')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'PRESENTE'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro");

                    b.Property<DateTime?>("HoraEntrada")
                        .HasColumnType("datetime")
                        .HasColumnName("hora_entrada");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime")
                        .HasColumnName("hora_salida");

                    b.HasKey("IdAsistencia")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FechaRegistro", "Estado" }, "idx_fecha_estado");

                    b.HasIndex(new[] { "EmpleadoId", "FechaRegistro" }, "unique_empleado_fecha")
                        .IsUnique();

                    b.ToTable("asistencias", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AuditoriaCambios", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_auditoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tabla_afectada");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdAuditoria")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TablaAfectada", "FechaCreacion" }, "idx_tabla_fecha");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id");

                    b.ToTable("auditoria_cambios", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Departamentos", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_departamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVO','INACTIVO')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'ACTIVO'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<int?>("IdJefeDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("id_jefe_departamento");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_departamento");

                    b.HasKey("IdDepartamento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdJefeDepartamento" }, "id_jefe_departamento");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DetalleEvaluaciones", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comentarios");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<int>("IdEvaluacion")
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion");

                    b.Property<int>("IdMetrica")
                        .HasColumnType("int")
                        .HasColumnName("id_metrica");

                    b.Property<sbyte>("Puntuacion")
                        .HasColumnType("tinyint")
                        .HasColumnName("puntuacion");

                    b.HasKey("IdDetalle")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMetrica" }, "id_metrica");

                    b.HasIndex(new[] { "IdEvaluacion", "IdMetrica" }, "unique_evaluacion_metrica")
                        .IsUnique();

                    b.ToTable("detalle_evaluaciones", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Empleados", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_empleado");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVO','INACTIVO','LICENCIA')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'ACTIVO'");

                    b.Property<DateOnly>("FechaContratacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_contratacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<int?>("JefeInmediatoId")
                        .HasColumnType("int")
                        .HasColumnName("jefe_inmediato_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("primer_apellido");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario_base");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("enum('FIJO','TEMPORAL','PRUEBA')")
                        .HasColumnName("tipo_contrato");

                    b.HasKey("IdEmpleado")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodigoEmpleado" }, "codigo_empleado")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "DepartamentoId" }, "idx_departamento");

                    b.HasIndex(new[] { "PuestoId" }, "idx_puesto");

                    b.HasIndex(new[] { "JefeInmediatoId" }, "jefe_inmediato_id");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EvaluacionesRendimiento", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comentarios");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ANULADA','APROBADA')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'PENDIENTE'");

                    b.Property<int>("EvaluadorId")
                        .HasColumnType("int")
                        .HasColumnName("evaluador_id");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<sbyte>("PuntuacionTotal")
                        .HasColumnType("tinyint")
                        .HasColumnName("puntuacion_total");

                    b.HasKey("IdEvaluacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EvaluadorId" }, "evaluador_id");

                    b.HasIndex(new[] { "EmpleadoId", "FechaInicio", "FechaFin" }, "idx_empleado_periodo");

                    b.ToTable("evaluaciones_rendimiento", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HorasExtras", b =>
                {
                    b.Property<int>("IdHoraExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_hora_extra");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHoraExtra"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("EstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','APROBADA','RECHAZADA')")
                        .HasColumnName("estado_solicitud")
                        .HasDefaultValueSql("'PENDIENTE'");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int?>("JefeApruebaId")
                        .HasColumnType("int")
                        .HasColumnName("jefe_aprueba_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo");

                    b.Property<string>("TipoHoraExtra")
                        .HasColumnType("enum('PENDIENTE','APROBADA','RECHAZADA')")
                        .HasColumnName("tipo_hora_extra");

                    b.HasKey("IdHoraExtra")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "FechaInicio" }, "idx_empleado_fecha");

                    b.HasIndex(new[] { "JefeApruebaId" }, "jefe_aprueba_id");

                    b.ToTable("horas_extras", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Incapacidades", b =>
                {
                    b.Property<int>("IdIncapacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_incapacidad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIncapacidad"));

                    b.Property<string>("ArchivoAdjunto")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("archivo_adjunto");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("diagnostico");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVA','FINALIZADA')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'ACTIVA'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("TipoIncapacidad")
                        .IsRequired()
                        .HasColumnType("enum('ENFERMEDAD','ACCIDENTE','MATERNIDAD','PATERNIDAD')")
                        .HasColumnName("tipo_incapacidad");

                    b.HasKey("IdIncapacidad")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "FechaInicio", "FechaFin" }, "idx_empleado_fechas");

                    b.ToTable("incapacidades", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Liquidaciones", b =>
                {
                    b.Property<int>("IdLiquidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_liquidacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLiquidacion"));

                    b.Property<decimal?>("AguinaldoProporcional")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("aguinaldo_proporcional")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CALCULADA', 'ANULADA')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'CALCULADA'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaLiquidacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_liquidacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<decimal?>("Indemnizacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("indemnizacion")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("MontoPreaviso")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_preaviso")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("MotivoLiquidacion")
                        .IsRequired()
                        .HasColumnType("enum('RENUNCIA','RENUNCIA_RESPONSABILIDAD_PATRONAL','DESPIDO_RESPONSABILIDAD_PATRONAL','DESPIDO_SIN_RESPONSABILIDAD', 'JUBILACION')")
                        .HasColumnName("motivo_liquidacion");

                    b.Property<decimal?>("OtrosConceptos")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("otros_conceptos")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("TotalLiquidacion")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_liquidacion");

                    b.Property<decimal?>("VacacionesPendientes")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vacaciones_pendientes")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("IdLiquidacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "FechaLiquidacion" }, "idx_empleado_fecha")
                        .HasDatabaseName("idx_empleado_fecha1");

                    b.ToTable("liquidaciones", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MetricasRendimiento", b =>
                {
                    b.Property<int>("IdMetrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metrica");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMetrica"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("NombreMetrica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_metrica");

                    b.Property<decimal>("Peso")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("peso");

                    b.HasKey("IdMetrica")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Estado" }, "idx_estado");

                    b.ToTable("metricas_rendimiento", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Nominas", b =>
                {
                    b.Property<int>("IdNomina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_nomina");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNomina"));

                    b.Property<decimal?>("Bonificaciones")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("bonificaciones")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("Deducciones")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("deducciones")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','PAGADA','ANULADA', 'APROBADA')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'PENDIENTE'");

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaActualizacion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal?>("HorasExtras")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("horas_extras")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("MontoHorasExtra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_horas_extra")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<DateTime>("PeriodoNomina")
                        .HasColumnType("datetime")
                        .HasColumnName("periodo_nomina");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("TotalBruto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_bruto");

                    b.Property<decimal>("TotalNeto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_neto");

                    b.HasKey("IdNomina")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "PeriodoNomina" }, "idx_empleado_periodo")
                        .HasDatabaseName("idx_empleado_periodo1");

                    b.ToTable("nominas", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Permisos", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("ComentariosRechazo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comentarios_rechazo");

                    b.Property<bool?>("ConGoceSalario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("con_goce_salario")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("EstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','APROBADA','RECHAZADA')")
                        .HasColumnName("estado_solicitud")
                        .HasDefaultValueSql("'PENDIENTE'");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateTime>("FechaPermiso")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_permiso");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int?>("JefeApruebaId")
                        .HasColumnType("int")
                        .HasColumnName("jefe_aprueba_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo");

                    b.HasKey("IdPermiso")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "FechaPermiso" }, "idx_empleado_fecha")
                        .HasDatabaseName("idx_empleado_fecha2");

                    b.HasIndex(new[] { "JefeApruebaId" }, "jefe_aprueba_id")
                        .HasDatabaseName("jefe_aprueba_id1");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Puestos", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_puesto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<sbyte?>("NivelJerarquico")
                        .HasColumnType("tinyint")
                        .HasColumnName("nivel_jerarquico");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_puesto");

                    b.Property<decimal?>("SalarioMaximo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario_maximo");

                    b.Property<decimal?>("SalarioMinimo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario_minimo");

                    b.HasKey("IdPuesto")
                        .HasName("PRIMARY");

                    b.ToTable("puestos", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Roles", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SaldoVacaciones", b =>
                {
                    b.Property<int>("IdSaldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_saldo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSaldo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<int>("DiasAcumulados")
                        .HasColumnType("int")
                        .HasColumnName("dias_acumulados");

                    b.Property<int?>("DiasDisfrutados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dias_disfrutados")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaActualizacion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdSaldo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "Anio" }, "unique_empleado_anio")
                        .IsUnique();

                    b.ToTable("saldo_vacaciones", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVO','INACTIVO','BLOQUEADO')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'ACTIVO'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId" }, "empleado_id")
                        .IsUnique();

                    b.HasIndex(new[] { "Estado" }, "idx_estado")
                        .HasDatabaseName("idx_estado1");

                    b.HasIndex(new[] { "NombreUsuario" }, "nombre_usuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.UsuariosRoles", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<string>("EstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','APROBADA','RECHAZADA')")
                        .HasColumnName("estado_solicitud")
                        .HasDefaultValueSql("'PENDIENTE'");

                    b.Property<DateTime?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdUsuarioRol")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RolId" }, "rol_id");

                    b.HasIndex(new[] { "UsuarioId", "RolId" }, "unique_usuario_rol")
                        .IsUnique();

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Vacaciones", b =>
                {
                    b.Property<int>("IdVacacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vacacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVacacion"));

                    b.Property<string>("ComentariosRechazo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comentarios_rechazo");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("EstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','APROBADA','RECHAZADA','DISFRUTANDO','COMPLETADA', 'CANCELADA')")
                        .HasColumnName("estado_solicitud")
                        .HasDefaultValueSql("'PENDIENTE'");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int?>("JefeApruebaId")
                        .HasColumnType("int")
                        .HasColumnName("jefe_aprueba_id");

                    b.HasKey("IdVacacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmpleadoId", "EstadoSolicitud" }, "idx_empleado_estado")
                        .HasDatabaseName("idx_empleado_estado1");

                    b.HasIndex(new[] { "FechaInicio", "FechaFin" }, "idx_fechas");

                    b.HasIndex(new[] { "JefeApruebaId" }, "jefe_aprueba_id")
                        .HasDatabaseName("jefe_aprueba_id2");

                    b.ToTable("vacaciones", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Aguinaldos", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("Aguinaldos")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("aguinaldos_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Asistencias", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("Asistencias")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("asistencias_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AuditoriaCambios", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Usuarios", "Usuario")
                        .WithMany("AuditoriaCambios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("auditoria_cambios_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Departamentos", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "JefeDepartamento")
                        .WithMany("Departamentos")
                        .HasForeignKey("IdJefeDepartamento")
                        .HasConstraintName("departamentos_ibfk_1");

                    b.Navigation("JefeDepartamento");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DetalleEvaluaciones", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.EvaluacionesRendimiento", "IdEvaluacionNavigation")
                        .WithMany("DetalleEvaluaciones")
                        .HasForeignKey("IdEvaluacion")
                        .IsRequired()
                        .HasConstraintName("detalle_evaluaciones_ibfk_1");

                    b.HasOne("DataAccessLayer.Entities.MetricasRendimiento", "IdMetricaNavigation")
                        .WithMany("DetalleEvaluaciones")
                        .HasForeignKey("IdMetrica")
                        .IsRequired()
                        .HasConstraintName("detalle_evaluaciones_ibfk_2");

                    b.Navigation("IdEvaluacionNavigation");

                    b.Navigation("IdMetricaNavigation");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Empleados", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Departamentos", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("empleados_ibfk_2");

                    b.HasOne("DataAccessLayer.Entities.Empleados", "JefeInmediato")
                        .WithMany("InverseJefeInmediato")
                        .HasForeignKey("JefeInmediatoId")
                        .HasConstraintName("empleados_ibfk_3");

                    b.HasOne("DataAccessLayer.Entities.Puestos", "Puesto")
                        .WithMany("Empleados")
                        .HasForeignKey("PuestoId")
                        .IsRequired()
                        .HasConstraintName("empleados_ibfk_1");

                    b.Navigation("Departamento");

                    b.Navigation("JefeInmediato");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EvaluacionesRendimiento", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("EvaluacionesRendimientoEmpleado")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("evaluaciones_rendimiento_ibfk_1");

                    b.HasOne("DataAccessLayer.Entities.Empleados", "Evaluador")
                        .WithMany("EvaluacionesRendimientoEvaluador")
                        .HasForeignKey("EvaluadorId")
                        .IsRequired()
                        .HasConstraintName("evaluaciones_rendimiento_ibfk_2");

                    b.Navigation("Empleado");

                    b.Navigation("Evaluador");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HorasExtras", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("HorasExtrasEmpleado")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("horas_extras_ibfk_1");

                    b.HasOne("DataAccessLayer.Entities.Empleados", "JefeAprueba")
                        .WithMany("HorasExtrasJefeAprueba")
                        .HasForeignKey("JefeApruebaId")
                        .HasConstraintName("horas_extras_ibfk_2");

                    b.Navigation("Empleado");

                    b.Navigation("JefeAprueba");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Incapacidades", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("Incapacidades")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("incapacidades_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Liquidaciones", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("liquidaciones_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Nominas", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("Nominas")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("nominas_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Permisos", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("PermisosEmpleado")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("permisos_ibfk_1");

                    b.HasOne("DataAccessLayer.Entities.Empleados", "JefeAprueba")
                        .WithMany("PermisosJefeAprueba")
                        .HasForeignKey("JefeApruebaId")
                        .HasConstraintName("permisos_ibfk_2");

                    b.Navigation("Empleado");

                    b.Navigation("JefeAprueba");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SaldoVacaciones", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("SaldoVacaciones")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("saldo_vacaciones_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Usuarios", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithOne("Usuarios")
                        .HasForeignKey("DataAccessLayer.Entities.Usuarios", "EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("usuarios_ibfk_1");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.UsuariosRoles", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Roles", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("usuarios_roles_ibfk_2");

                    b.HasOne("DataAccessLayer.Entities.Usuarios", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("usuarios_roles_ibfk_1");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Vacaciones", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Empleados", "Empleado")
                        .WithMany("VacacionesEmpleado")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("vacaciones_ibfk_1");

                    b.HasOne("DataAccessLayer.Entities.Empleados", "JefeAprueba")
                        .WithMany("VacacionesJefeAprueba")
                        .HasForeignKey("JefeApruebaId")
                        .HasConstraintName("vacaciones_ibfk_2");

                    b.Navigation("Empleado");

                    b.Navigation("JefeAprueba");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Departamentos", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Empleados", b =>
                {
                    b.Navigation("Aguinaldos");

                    b.Navigation("Asistencias");

                    b.Navigation("Departamentos");

                    b.Navigation("EvaluacionesRendimientoEmpleado");

                    b.Navigation("EvaluacionesRendimientoEvaluador");

                    b.Navigation("HorasExtrasEmpleado");

                    b.Navigation("HorasExtrasJefeAprueba");

                    b.Navigation("Incapacidades");

                    b.Navigation("InverseJefeInmediato");

                    b.Navigation("Liquidaciones");

                    b.Navigation("Nominas");

                    b.Navigation("PermisosEmpleado");

                    b.Navigation("PermisosJefeAprueba");

                    b.Navigation("SaldoVacaciones");

                    b.Navigation("Usuarios");

                    b.Navigation("VacacionesEmpleado");

                    b.Navigation("VacacionesJefeAprueba");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EvaluacionesRendimiento", b =>
                {
                    b.Navigation("DetalleEvaluaciones");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MetricasRendimiento", b =>
                {
                    b.Navigation("DetalleEvaluaciones");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Puestos", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Roles", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Usuarios", b =>
                {
                    b.Navigation("AuditoriaCambios");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
